## 00. Fundamentos de Pytorch

Vídeo de referencia: https://www.youtube.com/watch?v=Z_ikDlimN6A&t=3521s

Documentación de Pytorch: https://pytorch.org/docs/stable/index.html

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introducción a los tensores

Vídeo para entender el concepto de tensores: https://youtu.be/f5liqUk0ZTw

###Teoría:

* Los tensores se crean utilizando `torch.tensor()`

* Para ver la dimensión de un tensor : `nombre.ndim`

* Truco para saber la dimensión de un tensor: la dimensión coincide con el número de corchetes a la hora de declarar el tensor. Por ejemplo, un vector es un tensor de dimensión 1, ya que se utiliza un corchete, la matriz 2 y así.

* Para ver el valor almacenado en el tensor: `nombre.item()
`

* Los tensores son indexables, luego se puede acceder a la información mediante `nombre[indice]`


In [4]:
# Escalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
# MATRIZ
MATRIZ = torch.tensor([[1, 2],
                       [3, 4]])
MATRIZ

tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIZ.ndim

2

In [11]:
MATRIZ.shape

torch.Size([2, 2])

In [12]:
MATRIZ[0][1].item()

2

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[9, 8, 7],
                        [6, 5, 4],
                        [3, 2, 1]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

In [16]:
TENSOR[0][1][2].item()

6

In [17]:
TENSOR[1][2][0].item()

3

### Tensores aleatorios

Los tensores aleatorios son importantes ya que generalmetne se crea un tensor con números aleatorios y luego nuestro modelo ajusta eso valores aleatorios a los datos que tenemos.

In [18]:
# Crear un tensor de cualquier tamaño o shape
tensor_aleatorio = torch.rand(2, 4, 3)
tensor_aleatorio

tensor([[[0.6954, 0.1871, 0.5544],
         [0.9477, 0.2929, 0.0835],
         [0.2947, 0.3291, 0.3794],
         [0.8761, 0.9380, 0.8634]],

        [[0.6909, 0.0448, 0.5036],
         [0.4745, 0.6899, 0.4872],
         [0.4506, 0.1233, 0.4117],
         [0.3087, 0.6961, 0.3329]]])

In [19]:
tensor_aleatorio.ndim

3

In [20]:
tensor_aleatorio[1][2][2].item()

0.41167163848876953

In [21]:
# Tensor de formato imagen: colores, altura, anchura
tensor_imagen = torch.rand(3, 244, 244)
tensor_imagen.shape, tensor_imagen.ndim

(torch.Size([3, 244, 244]), 3)

### Tensores de unos y ceros


In [22]:
# Crear tensor con 0
ceros = torch.zeros(4, 1)
tensor_prueba = torch.rand(4, 4)
tensor_prueba * ceros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Crear tensor con 1
unos = torch.ones(3, 3)
unos

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Crear rango de tensores y tensores tipo

Los tensores tipo sirven para crear tensores de la misma dimensión que otro, sin tener que conocer cuál es esta dimensión.

Estos se pueden crear con zeros usando `torch.zeros_like(nombre)`, pero no con valores aleatorios

In [24]:
# El arange funciona igual que el range en Python
rango = torch.arange(1, 20, 2)
rango.shape

torch.Size([10])

In [25]:
# Tensores tipos de 0
replica_ceros = torch.zeros_like(rango)
replica_ceros, replica_ceros.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([10]))

### Parámetros

Los tres parámetros más importantes en la creación de tensores son:

*   `dtype`: Esto es el tipo de datos del tensor. Puede ser `torch.float16` o `torch.float32` o `torch.float64`. A mayor precisión (mayor valor númerico), menos velocdiad de cálculo.
*   `device`: El dispositivo en el que se encuentra el tensor. Puede ser CPU o GPU.
* `requires_grad`: Si queremos trabajar con el gradiente, lo veremos más adelante.


In [26]:
tensor_float_16 = torch.tensor([[3, 4],
                                [9, 8]],
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
tensor_float_16

tensor([[3., 4.],
        [9., 8.]], dtype=torch.float16)

In [27]:
tensor_float_16.dtype

torch.float16

In [28]:
# Cambiar tipo de datos de un tensor
tensor_float_32 = tensor_float_16.type(torch.float32)
tensor_float_32.dtype

torch.float32

### Errores

Los tres errores principales a la hora de trabajar con tesnores son:
* Tensores con tipos de datos diferentes.
* Tensores con una forma incorrecta (relacionado con la multiplicación).
* Tensor en dispositivos incorrectos (no se puede trabajar con tensores que se encuentren en diferentes dispositivos, uno en CPU y otro en GPU).

In [29]:
# Desmostración del error 1, el resultado es el tensor más preciso
resultado = tensor_float_16 * tensor_float_32
resultado, resultado.dtype

(tensor([[ 9., 16.],
         [81., 64.]]),
 torch.float32)

### Tomar información de los tensores

* `nombre.shape` nos dice la estructura del tensor. Por ejemplo si una matriz es 2x2 nos dara [2, 2] y así igual con tensores de mayor dimensión.

* Para ver el tipo de dato se utiliza `nombre.dtype`

* Para ver el dispositivo del tensor se utiliza `tensor.device`

In [30]:
tensor_prueba = torch.rand((2, 4, 3), dtype=torch.float16)

In [31]:
print(tensor_prueba)
print(f"\nTipo de datos: {tensor_prueba.dtype}")
print(f"Forma: {tensor_prueba.shape}")
print(f"Dispositivo: {tensor_prueba.device}")

tensor([[[0.4932, 0.3154, 0.3267],
         [0.9531, 0.1914, 0.7612],
         [0.1162, 0.1816, 0.7368],
         [0.4800, 0.4688, 0.0898]],

        [[0.8511, 0.6938, 0.1011],
         [0.0322, 0.4155, 0.6826],
         [0.2808, 0.1343, 0.2031],
         [0.1401, 0.4072, 0.7905]]], dtype=torch.float16)

Tipo de datos: torch.float16
Forma: torch.Size([2, 4, 3])
Dispositivo: cpu


In [32]:
# Cambiar el tipo de datos del tensor
tensor_32 = tensor_prueba.type(torch.float32)
tensor_32.dtype

torch.float32

In [34]:
# Cambiar el dispositivo de CPU a GPU
tensor_gpu = tensor_prueba.to("cuda")
tensor_gpu.device

device(type='cuda', index=0)

In [35]:
# Cambiar el dispositivo de GPU a CPU
tensor_cpu = tensor_gpu.to("cpu")
tensor_cpu.device

device(type='cpu')